version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.14
    commands:
      - mkdir -p package
      - pip install --upgrade pip
      - pip install -r requirements.txt -t package/

  build:
    commands:
      - cp -r upload_image_project package/
      - cp -r uploads package/
      - cp manage.py package/
      - cp lambda_function.py package/

artifacts:
  base-directory: package
  files:
    - '**/*'